backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "Blog Posts"
    name: "blog-posts"
    folder: "public/blog-posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Header Image",
          name: "image",
          widget: "image",
          required: False,
        }
      - { label: "Body", name: "body", widget: "markdown" }
